<div class="row">
<div class="col-md-6 form-group"><label>Nom</label><input type="text" name="nom" class="form-control @error('nom') is-invalid @enderror" value="{{ old('nom', optional($personnel)->nom) }}" required>@error('nom') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-6 form-group"><label>Prenom</label><input type="text" name="prenom" class="form-control @error('prenom') is-invalid @enderror" value="{{ old('prenom', optional($personnel)->prenom) }}" required>@error('prenom') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-6 form-group"><label>Sexe</label><select name="sexe" class="form-control @error('sexe') is-invalid @enderror" required><option value="">Choisir...</option><option value="M" @selected(old('sexe', optional($personnel)->sexe) === 'M')>M</option><option value="F" @selected(old('sexe', optional($personnel)->sexe) === 'F')>F</option></select>@error('sexe') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-6 form-group"><label>Date de naissance</label><input type="date" name="date_naissance" max="{{ now()->subDay()->toDateString() }}" class="form-control @error('date_naissance') is-invalid @enderror" value="{{ old('date_naissance', optional(optional($personnel)->date_naissance)->format('Y-m-d')) }}" required>@error('date_naissance') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-6 form-group"><label>Photo</label><input type="file" name="photo" class="form-control-file @error('photo') is-invalid @enderror" accept=".jpg,.jpeg,.png,.webp">@error('photo') <div class="invalid-feedback d-block">{{ $message }}</div> @enderror</div>
<div class="col-md-6 form-group d-flex align-items-end">@if(optional($personnel)->photo)<img src="{{ asset('storage/'.optional($personnel)->photo) }}" alt="Photo personnel" style="width:72px;height:72px;border-radius:18px;object-fit:cover;border:1px solid rgba(148,163,184,0.25);">@endif</div>
</div>
<div class="row">
<div class="col-md-4 form-group"><label>Fonction</label><select name="fonction" class="form-control @error('fonction') is-invalid @enderror" required data-enhance-select="true"><option value="">Choisir...</option>@foreach($fonctions as $fonction)<option value="{{ $fonction->label }}" @selected(old('fonction', optional($personnel)->fonction) === $fonction->label)>{{ $fonction->label }}</option>@endforeach</select>@error('fonction') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Departement</label><select name="departement" class="form-control @error('departement') is-invalid @enderror" required data-enhance-select="true"><option value="">Choisir...</option>@foreach($departements as $departement)<option value="{{ $departement->label }}" @selected(old('departement', optional($personnel)->departement) === $departement->label)>{{ $departement->label }}</option>@endforeach</select>@error('departement') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Niveau d'etude</label><select name="niveau_etude" class="form-control @error('niveau_etude') is-invalid @enderror" required data-enhance-select="true"><option value="">Choisir...</option>@foreach($niveauxEtude as $niveauEtude)<option value="{{ $niveauEtude->label }}" @selected(old('niveau_etude', optional($personnel)->niveau_etude) === $niveauEtude->label)>{{ $niveauEtude->label }}</option>@endforeach</select>@error('niveau_etude') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-6 form-group"><label>Ecole</label><select name="school_id" class="form-control @error('school_id') is-invalid @enderror" data-enhance-select="true"><option value="">Choisir...</option>@foreach($schools as $school)<option value="{{ $school->id }}" @selected((string) old('school_id', optional($personnel)->school_id) === (string) $school->id)>{{ $school->name }}{{ $school->city ? ' - '.$school->city : '' }}</option>@endforeach</select>@error('school_id') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-6 form-group"><label>Classe rattachee</label><select name="school_class_id" class="form-control @error('school_class_id') is-invalid @enderror" data-enhance-select="true"><option value="">Choisir...</option>@foreach($schoolClasses as $schoolClass)<option value="{{ $schoolClass->id }}" @selected((string) old('school_class_id', optional($personnel)->school_class_id) === (string) $schoolClass->id)>{{ $schoolClass->name }} - {{ $schoolClass->school?->name }} - {{ $schoolClass->academicYear?->label }}</option>@endforeach</select>@error('school_class_id') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-6 form-group"><label>Domaine d'etude</label><input type="text" name="domaine_etude" class="form-control @error('domaine_etude') is-invalid @enderror" value="{{ old('domaine_etude', optional($personnel)->domaine_etude) }}">@error('domaine_etude') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-6 form-group"><label>Annees d'experience</label><input type="number" name="annees_experience" min="0" max="80" class="form-control @error('annees_experience') is-invalid @enderror" value="{{ old('annees_experience', optional($personnel)->annees_experience ?? 0) }}" required>@error('annees_experience') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-4 form-group"><label>CIN</label><input type="text" name="numero_cin" class="form-control @error('numero_cin') is-invalid @enderror" value="{{ old('numero_cin', optional($personnel)->numero_cin) }}" required>@error('numero_cin') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Delivrance CIN</label><input type="date" name="date_delivrance_cin" max="{{ now()->toDateString() }}" class="form-control @error('date_delivrance_cin') is-invalid @enderror" value="{{ old('date_delivrance_cin', optional(optional($personnel)->date_delivrance_cin)->format('Y-m-d')) }}" required>@error('date_delivrance_cin') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Lieu de delivrance CIN</label><input type="text" name="lieu_delivrance_cin" class="form-control @error('lieu_delivrance_cin') is-invalid @enderror" value="{{ old('lieu_delivrance_cin', optional($personnel)->lieu_delivrance_cin) }}" required>@error('lieu_delivrance_cin') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-12 form-group"><label>N rue</label><input type="text" name="adresse_rue" class="form-control @error('adresse_rue') is-invalid @enderror" value="{{ old('adresse_rue', optional($personnel)->adresse_rue) }}">@error('adresse_rue') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-4 form-group"><label>Ville</label><input type="text" name="adresse_ville" class="form-control @error('adresse_ville') is-invalid @enderror" value="{{ old('adresse_ville', optional($personnel)->adresse_ville) }}">@error('adresse_ville') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Gouvernorat</label><input type="text" name="adresse_gouvernorat" class="form-control @error('adresse_gouvernorat') is-invalid @enderror" value="{{ old('adresse_gouvernorat', optional($personnel)->adresse_gouvernorat) }}">@error('adresse_gouvernorat') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Code postale</label><input type="text" name="adresse_code_postal" class="form-control @error('adresse_code_postal') is-invalid @enderror" value="{{ old('adresse_code_postal', optional($personnel)->adresse_code_postal) }}">@error('adresse_code_postal') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-4 form-group"><label>Telephone</label><input type="text" name="telephone" class="form-control @error('telephone') is-invalid @enderror" value="{{ old('telephone', optional($personnel)->telephone) }}" required>@error('telephone') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Email</label><input type="email" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email', optional($personnel)->email) }}">@error('email') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Numero CNSS</label><input type="text" name="numero_cnss" class="form-control @error('numero_cnss') is-invalid @enderror" value="{{ old('numero_cnss', optional($personnel)->numero_cnss) }}">@error('numero_cnss') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
<div class="row">
<div class="col-md-4 form-group"><label>Date d'embauche</label><input type="date" name="date_embauche" max="{{ now()->toDateString() }}" class="form-control @error('date_embauche') is-invalid @enderror" value="{{ old('date_embauche', optional(optional($personnel)->date_embauche)->format('Y-m-d')) }}" required>@error('date_embauche') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group"><label>Manager</label><select name="manager_id" class="form-control @error('manager_id') is-invalid @enderror" data-enhance-select="true"><option value="">Aucun</option>@foreach($managers as $manager)<option value="{{ $manager->id }}" @selected((string) old('manager_id', optional($personnel)->manager_id) === (string) $manager->id)>{{ $manager->nom }} {{ $manager->prenom }}</option>@endforeach</select>@error('manager_id') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
<div class="col-md-4 form-group d-flex align-items-end"><div class="form-check mb-3"><input type="checkbox" name="create_user_account" value="1" class="form-check-input" id="create_user_account" @checked(old('create_user_account'))><label class="form-check-label" for="create_user_account">Creation d'un user</label></div></div>
</div>
<div class="row">
<div class="col-md-6 form-group"><label>Type de user a creer</label><select name="user_role" class="form-control @error('user_role') is-invalid @enderror" data-enhance-select="true"><option value="">Choisir...</option>@foreach($roles as $role)<option value="{{ $role->name }}" @selected(old('user_role', $linkedUserRole) === $role->name)>{{ $role->name }}</option>@endforeach</select>@error('user_role') <div class="invalid-feedback">{{ $message }}</div> @enderror</div>
</div>
